version: '3.4'

networks:
  backend:
  frontend:

services:
  blazorserverwebui:
    container_name: blazor-web-ui
    image: ${DOCKER_REGISTRY-}blazorserverwebui
    build:
      context: .
      dockerfile: BlazorServerWebUI/Dockerfile
    ports:
    - 8002:80
    networks:
    - frontend

  authenticationwebapi:
    container_name: authentication-api
    image: ${DOCKER_REGISTRY-}authenticationwebapi
    build:
      context: .
      dockerfile: AuthenticationWebApi/Dockerfile
    networks:
    - backend
    environment:
    - DB_HOST=useraccountauthdb
    - DB_NAME=user_accounts
    - DB_SA_PASSWORD=password@12345

  useraccountauthdb:
    container_name: user-account-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment: 
     - ACCEPT_EULA=Y
     - SA_PASSWORD=password@12345
    networks:
     - backend
    ports:
     - 18001:1433

  apigateway:
    container_name: web-gateway-api
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    ports:
    - 8001:80 
    networks:
    - backend
    - frontend

  carwebapi:
    container_name: car-api
    image: ${DOCKER_REGISTRY-}carwebapi
    build:
      context: .
      dockerfile: CarWebApi/Dockerfile
    networks:
    - backend
    environment:
    - DB_HOST=cardb
    - DB_NAME=car
    - POSTGRES_PASSWORD=@2o!&69

  cardb:
    container_name: car-db
    image: postgres
    restart: always
    environment:
    - POSTGRES_PASSWORD=@2o!&69
    networks:
    - backend
    ports:
    - 18002:5432