version: '3.4'

networks:
  backend:
  frontend:

services:
  blazorserverwebui:
    container_name: blazor-web-ui
    image: ${DOCKER_REGISTRY-}blazorserverwebui
    build:
      context: .
      dockerfile: BlazorServerWebUI/Dockerfile
    ports:
    - 8002:80
    networks:
    - frontend

  authenticationwebapi:
    container_name: authentication-api
    image: ${DOCKER_REGISTRY-}authenticationwebapi
    build:
      context: .
      dockerfile: AuthenticationWebApi/Dockerfile
    networks:
    - backend

  apigateway:
    container_name: web-gateway-api
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    ports:
    - 8001:80 
    networks:
    - backend
    - frontend
